---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql
  labels:
    {{- include "airflowpostgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgresql-admin-password: {{ .Values.postgresql.admin_password | default "6d6ecdf7805ee81b" | quote }}
  postgresql-password: {{ .Values.postgresql.password | default "6a9e5cf7" | quote }}
  postgresql-user: {{ .Values.postgresql.user | default "bn_airflow" | quote }}
  postgresql-database: {{ .Values.postgresql.user | default "bitnami_airflow" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-redis
  labels:
    {{- include "airflowredis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | default "ad2a251b" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow
  labels:
    {{- include "airflowscheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  airflow-password: {{ .Values.airflow.password | default "f816c493" | quote }}
  airflow-fernetKey: {{ .Values.airflow.fernetKey | default "SJbwFs6Ms6R5Gu8ek9BoJhJH9vEU6dVYZLWJcW1KBEY=" | quote }}
  webserver-secret-key: {{ .Values.airflow.fernetKey | default "ff5669cc17a95211" | quote }}
  oauth-api-base-url: {{ .Values.oauth.api_base_url | default "https://keycloak/auth/realms/my-realm/protocol/openid-connect" | quote }}
  oauth-token-url: {{ .Values.oauth.token_url | default "https://keycloak/auth/realms/my-realm/protocol/openid-connect/token" | quote }}
  oauth-authorize-url: {{ .Values.oauth.authorize_url | default "https://keycloak/auth/realms/my-realm/protocol/openid-connect/auth" | quote }}
  oauth-logout-redirect-url: {{ .Values.oauth.authorize_url | default "https://keycloak/auth/realms/my-realm/protocol/openid-connect/logout?client_id=aflow" | quote }}
  oauth-client-id: {{ .Values.oauth.client_id | default "aflow" | quote }}
  oauth-client-secret: {{ .Values.oauth.client_secret | default "79a1a5871fb52d3c0c922b878ff05e0b" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-proxy
  annotations:
    kubernetes.io/service-account.name:
      {{ include "airflowproxy.serviceAccountName" . }}
type: kubernetes.io/service-account-token
