---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflow.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflowredis.serviceAccountName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airflowproxy.serviceAccountName" . }}
# DISABLE OAUTH
#  annotations:
#    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"airflow"}}'
