---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql-headless
  labels:
    {{- include "airflowpostgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    {{- include "airflowpostgresql.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgresql
  labels:
    {{- include "airflowpostgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    {{- include "airflowpostgresql.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis-headless
  labels:
    {{- include "airflowredis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "airflowredis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis-master
  labels:
    {{- include "airflowredis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: redis
      nodePort: null
  selector:
    {{- include "airflowredis.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  labels:
    {{- include "airflowweb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    {{- include "airflowweb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker-headless
  labels:
    {{- include "airflowworker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: worker
      port: 8793
      targetPort: worker
  selector:
    {{- include "airflowworker.selectorLabels" . | nindent 4 }}
