matrix:
  - name: Markdown
    aspell:
      lang: en
      # ignore-case: true
    dictionary:
      encoding: utf-8
      wordlists:
        - .wordlist
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - '!scratch/**|!**/INFO.md|!venv/**|**/*.md'
    default_encoding: utf-8
