replicaCountScheduler: 1
replicaCountWeb: 1
replicaCountWorker: 1
replicaCountPostgresql: 1
replicaCountRedis: 1
imageScheduler:
  repository: quay.io/eformat/airflow-scheduler
  pullPolicy: Always
  tag: "2.5.1"
imageWeb:
  repository: quay.io/eformat/airflow-web
  pullPolicy: Always
  tag: "2.5.1"
imageWorker:
  repository: quay.io/eformat/airflow-worker
  pullPolicy: Always
  tag: "2.5.1"
imageGitSync:
  repository: quay.io/eformat/git-sync
  pullPolicy: Always
  tag: "3.5.1"
imagePostgresql:
  repository: registry.redhat.io/rhel8/postgresql-13
  pullPolicy: Always
  tag: "1-101"
imageRedis:
  repository: registry.redhat.io/rhel8/redis-6
  pullPolicy: Always
  tag: "1-102"
imagePullSecrets: []
nameOverrideScheduler: ""
fullnameOverrideScheduler: ""
nameOverrideWeb: ""
fullnameOverrideWeb: ""
nameOverrideWorker: ""
fullnameOverrideWorker: ""
nameOverridePostgresql: ""
fullnameOverridePostgresql: ""
nameOverrideRedis: ""
fullnameOverrideRedis: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
  nameRedis: ""
  nameProxy: ""
podAnnotations: {}
resourcesGitSync:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesScheduler:
  limits:
    cpu: 750m
    memory: 1.5Gi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesWeb:
  limits:
    cpu: 750m
    memory: 1.5Gi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesWorker:
  limits:
    cpu: 750m
    memory: 1.5Gi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesPostgresql:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
resourcesRedis:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi
gitSync:
  repo: ""
  dest: ""
  branch: ""
  wait: ""
webserver:
  secret_key: ""
oauth:
  api_base_url: ""
  token_url: ""
  authorize_url: ""
  logout_redirect_url: ""
  client_id: ""
  client_secret: ""
postgresql:
  admin_password: ""
  user: ""
  password: ""
  database: ""
  accessModes:
    - ReadWriteOnce
  storage: 2Gi
redis:
  password: ""
  accessModes:
    - ReadWriteOnce
  storage: 2Gi
airflow:
  password: ""
  fernetKey: ""
avp:
  secretPath: ""
route:
  host: ""
metrics:
  path: "/admin/metrics"
  interval: "10s"
